apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: mlflow
    targetRevision: 5.1.17
    helm:
      releaseName: mlflow
      values: |
        image:
          repository: bitnamilegacy/mlflow
        gitImage:
          repository: bitnamilegacy/git
        waitContainer:
          image:
            repository: bitnamilegacy/os-shell
        volumePermissions:
          image:
            repository: bitnamilegacy/os-shell
        tracking:
          persistence:
            enabled: false
        service:
          type: ClusterIP
          port: 5000
        defaultArtifactRoot: file:///mlruns
        auth:
          enabled: false
        postgresql:
          enabled: true
          image:
            repository: bitnamilegacy/postgresql
          primary:
            persistence:
              enabled: false
          volumePermissions:
            image:
              repository: bitnamilegacy/os-shell
          metrics:
            image:
              repository: bitnamilegacy/postgres-exporter
        minio:
          enabled: true
          image:
            repository: bitnamilegacy/minio
          clientImage:
            repository: bitnamilegacy/minio-client
          persistence:
            enabled: false
          volumePermissions:
            image:
              repository: bitnamilegacy/os-shell
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true