apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: mlflow
    targetRevision: 5.1.17
    helm:
      releaseName: mlflow
      values: |
        image:
          repository: bitnamilegacy/mlflow
        gitImage:
          repository: bitnamilegacy/git
        waitContainer:
          image:
            repository: bitnamilegacy/os-shell
        volumePermissions:
          image:
            repository: bitnamilegacy/os-shell
        tracking:
          service:
            type: ClusterIP
            ports:
              http: 5000
          persistence:
            enabled: false
          auth:
            enabled: true
        defaultArtifactRoot: file:///mlruns
        postgresql:
          enabled: true
          image:
            repository: bitnamilegacy/postgresql
          primary:
            persistence:
              enabled: false
          volumePermissions:
            image:
              repository: bitnamilegacy/os-shell
          metrics:
            image:
              repository: bitnamilegacy/postgres-exporter
        minio:
          enabled: true
          image:
            repository: bitnamilegacy/minio
          clientImage:
            repository: bitnamilegacy/minio-client
          persistence:
            enabled: false
          volumePermissions:
            image:
              repository: bitnamilegacy/os-shell
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true